# Generated by Django 4.0.3 on 2022-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sexe',
            field=models.CharField(default='Mix', max_length=50),
        ),
    ]
