# Generated by Django 4.0.3 on 2022-03-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_products_description_products_remise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_main',
            field=models.ImageField(upload_to='products'),
        ),
    ]
